# Generated by Django 5.0.7 on 2025-01-08 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='cricket.tournament'),
            preserve_default=False,
        ),
    ]
