# Generated by Django 5.0.7 on 2025-01-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0004_match_tournment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='tournment',
            new_name='tournament',
        ),
    ]
