# Generated by Django 5.0.7 on 2025-01-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0006_alter_match_tournament'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_type',
        ),
    ]
