# Generated by Django 4.1.13 on 2024-06-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.CharField(blank=True, choices=[('beaumont', 'Beaumont'), ('mondiale', 'Mondiale')], max_length=32, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('beaumont.smith_and_riley', 'SmithAndRiley'), ('beaumont.toll', 'TollGlobal'), ('beaumont.team', 'TeamTransport'), ('mondiale.ex_word', 'ExWork'), ('mondiale.detention', 'Detention'), ('mondiale.Domestic', 'SeaDomestic')], max_length=32, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('version', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JsonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.CharField(blank=True, choices=[('beaumont', 'Beaumont'), ('mondiale', 'Mondiale')], max_length=32, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('beaumont.smith_and_riley', 'SmithAndRiley'), ('beaumont.toll', 'TollGlobal'), ('beaumont.team', 'TeamTransport'), ('mondiale.ex_word', 'ExWork'), ('mondiale.detention', 'Detention'), ('mondiale.Domestic', 'SeaDomestic')], max_length=32, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='high(1) to low(5)')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='autotest.input')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='autotest.jsondata')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('categories', models.ManyToManyField(to='autotest.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='source, category etc.,', max_length=32)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
                'unique_together': {('type', 'name')},
            },
        ),
        migrations.AddField(
            model_name='input',
            name='groups',
            field=models.ManyToManyField(blank=True, to='autotest.inputgroup'),
        ),
        migrations.AddField(
            model_name='input',
            name='json',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='autotest.jsondata'),
        ),
        migrations.AddField(
            model_name='input',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_inputs', to='autotest.input'),
        ),
        migrations.AddField(
            model_name='category',
            name='testcases',
            field=models.ManyToManyField(related_name='categories', to='autotest.testcase'),
        ),
    ]
