# Generated by Django 4.1.13 on 2024-06-15 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(blank=True, choices=[('Test', 'TEST'), ('Development', 'DEVELOPMENT'), ('Production', 'PRODUCTION')], max_length=32, null=True)),
                ('testcase_id', models.CharField(help_text='TC_ID_01', max_length=255)),
                ('scenario', models.CharField(max_length=255)),
                ('cases', models.TextField(help_text='\n        Given external user is in Login page\n        When external user enters <Email> and <Password>\n        Then external user should login to the page\n        ', max_length=255)),
                ('test_data', models.TextField(blank=True, max_length=255, null=True)),
                ('actual_result', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pass', 'PASS'), ('Failed', 'FAILED'), ('Running', 'RUNNING'), ('Stopped', 'STOPPED')], default=None, max_length=32)),
                ('developer_status', models.TextField(blank=True, null=True)),
                ('retest_status', models.CharField(blank=True, choices=[('Pass', 'PASS'), ('Failed', 'FAILED'), ('Running', 'RUNNING'), ('Stopped', 'STOPPED')], max_length=32, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('version', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JsonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(blank=True, choices=[('Test', 'TEST'), ('Development', 'DEVELOPMENT'), ('Production', 'PRODUCTION')], max_length=32, null=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='high(1) to low(5)')),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='manual_test.input')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manual_test.projectlist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('testcases', models.ManyToManyField(related_name='categories', to='manual_test.testcase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_state', models.CharField(max_length=255)),
                ('related_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('testcases', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manual_test.testcase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='project name, testmodule etc.,', max_length=32)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
                'unique_together': {('type', 'name')},
            },
        ),
        migrations.AddField(
            model_name='input',
            name='groups',
            field=models.ManyToManyField(blank=True, to='manual_test.inputgroup'),
        ),
        migrations.AddField(
            model_name='input',
            name='json',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='manual_test.jsondata'),
        ),
        migrations.AddField(
            model_name='input',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_inputs', to='manual_test.input'),
        ),
        migrations.AddField(
            model_name='input',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manual_test.projectlist'),
        ),
    ]
