# Generated by Django 5.0.7 on 2025-01-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='json',
        ),
        migrations.RemoveField(
            model_name='input',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='priority',
        ),
        migrations.AlterField(
            model_name='testmodule',
            name='testcases',
            field=models.ManyToManyField(related_name='testmodules', to='manual_test.testcase'),
        ),
    ]
