# Generated by Django 4.1.13 on 2024-06-15 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JiraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('api_token', models.CharField(blank=True, max_length=500, null=True)),
                ('related_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_user_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JiraIssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JiraPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JiraRequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JiraStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JiraTicketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('project_key', models.CharField(max_length=50)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('issue_type', models.CharField(choices=[('Task', 'TASK'), ('Bug', 'BUG'), ('Story', 'STORY')], default='Task', max_length=50)),
                ('uuid', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_key', models.CharField(blank=True, max_length=50, null=True)),
                ('request_type', models.CharField(choices=[('New Request', 'NEW REQUEST'), ('Re Issue Request', 'RE ISSUE REQUEST')], default='New Request', max_length=50)),
                ('priority', models.CharField(choices=[('High', 'HIGH'), ('Medium', 'MEDIUM'), ('Low', 'LOW')], default='High', max_length=50)),
                ('status', models.CharField(choices=[('To Do', 'TO DO'), ('On Hold', 'ON HOLD'), ('In Progress', 'IN PROGRESS'), ('Testing', 'TESTING'), ('Done', 'DONE')], default='To Do', max_length=50)),
                ('assign_to', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('jira_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jira_ticket_detail', to='jira_integration.jirainfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
